### ISSUE TITLE
Use without Google Oauth

### ISSUE THREAD

**Issue by BurnsGG** [FaustoNisida/Chatbot-Long-Short-Term-Memory#1]
I wanted to test the code without Google services.
My API key is correct.

```
   if(!user) {
      return alert('To initiate a conversation with the bot, please log in first.');
    }
```

So I removed this code is this okay?

**Comment by BurnsGG** [comment]
{
    "message": "Request failed with status code 401",
    "name": "Error",
    "stack": "Error: Request failed with status code 401\n    at createError (C:\\Users\\Burnx\\chatbot\\server\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\Burnx\\chatbot\\server\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\Burnx\\chatbot\\server\\node_modules\\axios\\lib\\adapters\\http.js:322:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "OpenAI/NodeJS/3.2.1",
        "Authorization": "Bearer <..>",
        "Content-Length": 60
      },
      "method": "post",
      "data": "{\"model\":\"text-embedding-ada-002\",\"input\":\"\\nStudent: dzad\"}",
      "url": "https://api.openai.com/v1/embeddings"
    },
    "status": 401
  }

**Comment by BurnsGG** [comment]
I learned how to use google auth.

**Comment by FaustoNisida** [comment]
> I learned how to use google auth.

I'm happy to hear it. 
Feel free to ask again if you have a new issue!
