### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Jaroslab** [FaustoNisida/Chatbot-Long-Short-Term-Memory#2]
Hello, I entered the address http://localhost:5173/ in Google OAuth, but when I try to log in, a blank white window appears and that's it.

**Comment by FaustoNisida** [comment]
You have to add the following URIs:
![image](https://user-images.githubusercontent.com/115468971/222910543-27f74bf3-3634-4c08-be70-a9067237d182.png)
![image](https://user-images.githubusercontent.com/115468971/222910721-a2056c1b-3991-4c9c-ae4d-28c9629a7d82.png)

**Comment by Jaroslab** [comment]
Thanks!

**Comment by FaustoNisida** [comment]
> Thanks!

You are welcome!
